### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by zeuszapper** [INFO-526-S24/project-final-RoboCops#2]
The following is the peer review of the project proposal by Insight Architect . The team members that participated in this review are 

- Kaarthik Sai Patibandla  - @zeuszapper
- Shreemithra Naveen - @shreemithran
- Ayesha Khatun - @ayeshakhatunsujana
- Eeshaan Sourabh Reddy Mummila - @EeshaanReddy
- Anusha Nagaraja - @anusharaj1997
- Amaan Mohammed Yunus Salim Mulla- @amaanam

**- Describe the goal of the project.**
   
The project's goal is to investigate how `psychological traits`, `internalized bias`, and `socioeconomic factors` interact in the setting of police violence occurrences. They want to support evidence-based policymaking targeted at promoting fairness and justice on a larger scale by integrating a single `Washington state` dataset.

**- Describe the data used or collected.**

They have used the `PoliceKillingUS.csv` dataset, which they acquired through Kaggle and which contains attributes mostly related to `income`, `poverty rates`, and `demographics of the population`. Even though there are a lot of variables in this dataset, they might improve their proposal by adding more dataset dimensions. Given that Kaggle datasets don't always adhere to standards, we advise, if at all possible, looking through datasets from reliable sources or websites to guarantee the accuracy and quality of the data.

**- Describe how the research question will be answered, e.g. what approaches / methods will be used.**

1. The suggested method for answering the first study question entails using bar and column plots to graphically depict underlying socioeconomic disparities. A half-eye plot will also be used in the analysis to perform regression analysis and look at the connection between socioeconomic variables and instances of police use of force.

2. The second study topic explores whether there is a greater tendency for cops to belong to particular racial groupings. The strategy to deal with this is to use column plots and ggmap plots in conjunction with calculated variables called "Shooting Intensity." In addition, heatmaps and stacked bar plots will be employed in the research to clarify the significance of individual variables.

`Suggestion :`  Creating a dashboard concept and adding interactivity are two ideas to improve the process. This would provide a more dynamic and intuitive data exploration.

**- Is there anything that is unclear from the proposal?**

Certainly, the clarity of both the questions and their respective approaches is evident.

**- Provide constructive feedback on how the team might be able to improve their project.**

To illustrate the level of police force, one idea is to include `3D surface plots`, which would add a more complex viewpoint to the research. Furthermore, adding a heat map to show the geographical distribution of police force intensity in various locations could offer a thorough understanding of regional differences. This method may reveal high- and low-intensity patterns or clusters, enhancing the analysis even more.

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**

Plot 1 of research question 2 is notable because it aims to provide a comprehensive perspective of `spatial` and `quantitative` data by combining column charts and leaflet or ggmap plots. Within this visualization framework, we are eager to investigate the best interactive features that improve user engagement and enable dynamic data exploration.

**- Provide constructive feedback on any issues with file and/or code organization.**

The proposal seems well-organized, however it is difficult to assess its structure without access to the code. Regarding input, giving a more detailed timeline, taking into account that April 15th might be far off for only the proposal phase, and clearly identifying assignees could improve communication and cooperation.

**- (Optional) Any further comments or feedback?**

We highly recommend broadening the scope of the dataset selection, considering that the chosen dataset focuses solely on Washington state. According to Google, Washington has relatively low fatal police shootings compared to New Mexico. Opting for a dataset encompassing all states and comparing across the country would provide a more comprehensive understanding of the issue.

Way to go , All The Best  !!!!

**Comment by Peter-Yeh-coder** [comment]
**To illustrate the level of police force, one idea is to include 3D surface plots, which would add a more complex viewpoint to the research. Furthermore, adding a heat map to show the geographical distribution of police force intensity in various locations could offer a thorough understanding of regional differences. This method may reveal high- and low-intensity patterns or clusters, enhancing the analysis even more.**

We'll keep this in mind, but it is unlikely that we will use 3D plots since adding that extra dimension could make it difficult for viewers to interpret properly.

**The proposal seems well-organized, however it is difficult to assess its structure without access to the code. Regarding input, giving a more detailed timeline, taking into account that April 15th might be far off for only the proposal phase, and clearly identifying assignees could improve communication and cooperation.**

The timeline will be adjusted to designate roles at the next meeting. The code structure for table generation in the proposal was deemed unnecessary but will be done for plot generation or data wrangling

**We highly recommend broadening the scope of the dataset selection, considering that the chosen dataset focuses solely on Washington state. According to Google, Washington has relatively low fatal police shootings compared to New Mexico. Opting for a dataset encompassing all states and comparing across the country would provide a more comprehensive understanding of the issue.**

The proposal specifically mentions that the Washington Post covers all fifty states and DC. To account for the misunderstanding, the introduction was edited to explicitly state this fact at the beginning of the proposal.
